### ISSUE TITLE
난이도별로 단어를 나누기

### ISSUE THREAD

**Issue by krikit** [kakaonlp-internship2018/wsd#3]
95% 이상의 의미 쏠림이 있는 쉬운 단어, entropy가 높은 어려운 단어, 나머지 가운데 영역의 단어로 나눈다.

**Comment by hubert-lee** [comment]
@ene5135 
<img width="1182" alt="2018-08-17 6 04 46" src="https://user-images.githubusercontent.com/3006174/44257969-9ec73300-a248-11e8-81ca-cc93bb3b512f.png">

엔트로피 개념은 맨날 봐도 헷갈리는데요, 저도 한번에 와닿지 않아서 간단하게 코드로 만들어봤어요.
세미나 자료 준비하실 때, 예제로 보여주시면 아마 듣는 분들이 이해가 잘 되실듯 하여 코멘트 드립니다~

**Comment by ene5135** [comment]
감사합니다 ㅠ
말씀해주신대로 발표할때 엔트로피도 예제를 통해 잘 설명드리도록 하겠습니다!
